name: PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  gemini-review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/run-gemini-cli@v0
        with:
          command: 'review'
        env:
          # This secret is required for the Gemini review.
          # You can get a key from Google AI Studio.
          GEMINI_API_KEY: AIzaSyCTQw6sNJKqiTk_0UojxDo9N3G9vAie-3E

  coderabbit-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Coderabbit Review
        uses: coderabbitai/coderabbit-action@v1
        with:
          # This secret is required for the Coderabbit review.
          # You can get a key from your Coderabbit dashboard.
          CODERABBIT_API_KEY: cr-745bc9983f5bf1b1d090bcda39348e497f9f62f09e7214614d4007e6a8
